// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class QuickTellerSuiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void quickTellerTestcase() {
    driver.get("https://www.quickteller.com/");
    driver.manage().window().setSize(new Dimension(1074, 824));
    driver.findElement(By.cssSelector(".btn__login")).click();
    driver.findElement(By.id("accountLoginFormUsername")).click();
    driver.findElement(By.id("accountLoginFormUsername")).click();
    driver.findElement(By.id("accountLoginFormUsername")).click();
    driver.findElement(By.id("accountLoginFormUsername")).sendKeys("07030574390");
    driver.findElement(By.id("accountLoginFormPassword")).click();
    driver.findElement(By.id("accountLoginFormPassword")).sendKeys("password");
    driver.findElement(By.id("accountLoginFormButton")).click();
    driver.close();
  }
  @Test
  public void quicktellerpasswordusername() {
    driver.get("https://www.quickteller.com/");
    driver.manage().window().setSize(new Dimension(1074, 824));
    driver.findElement(By.cssSelector(".btn__login")).click();
    driver.findElement(By.id("accountLoginFormUsername")).click();
    driver.findElement(By.id("accountLoginFormUsername")).sendKeys("j");
    driver.findElement(By.id("accountLoginFormUsername")).sendKeys("joyobayagbonna@yahoo.com");
    driver.findElement(By.id("accountLoginFormPassword")).click();
    driver.findElement(By.id("accountLoginFormPassword")).sendKeys("Bernice2017");
    driver.findElement(By.id("accountLoginFormButton")).click();
    driver.close();
  }
  @Test
  public void signup() {
    driver.get("https://www.quickteller.com/");
    driver.manage().window().setSize(new Dimension(1074, 824));
    driver.findElement(By.cssSelector(".btn__signup")).click();
    driver.findElement(By.id("accountRegisterFormFirstname")).click();
    driver.findElement(By.id("accountRegisterFormFirstname")).sendKeys("Joy");
    driver.findElement(By.id("accountRegisterFormLastname")).click();
    driver.findElement(By.id("accountRegisterFormLastname")).sendKeys("Oba");
    driver.findElement(By.id("accountRegisterFormEmail")).click();
    driver.findElement(By.id("accountRegisterFormEmail")).sendKeys("joy-oba@gmail.com");
    driver.findElement(By.id("mobileNumber")).click();
    driver.findElement(By.id("mobileNumber")).sendKeys("09099447771");
    driver.findElement(By.id("accountRegisterFormPassword")).click();
    driver.findElement(By.id("accountRegisterFormPassword")).sendKeys("Bernice2017");
    driver.findElement(By.id("accountRegisterFormReferral")).click();
    driver.findElement(By.cssSelector(".clearfix:nth-child(6) > .col-md-12")).click();
    driver.findElement(By.id("accountRegisterFormButton")).click();
    driver.findElement(By.id("accountActivateCodeFormButton")).click();
    driver.close();
  }
  @Test
  public void forgotpassword() {
    driver.get("https://www.quickteller.com/");
    driver.manage().window().setSize(new Dimension(1074, 824));
    driver.findElement(By.cssSelector(".btn__login")).click();
    driver.findElement(By.id("accountLoginFormUsername")).click();
    driver.findElement(By.id("accountLoginFormUsername")).sendKeys("joyobayagbonna");
    driver.findElement(By.id("accountLoginFormButton")).click();
    driver.findElement(By.cssSelector(".text__c--light-blue > span")).click();
    driver.findElement(By.id("accountResetPasswordEmail")).click();
    driver.findElement(By.id("accountResetPasswordEmail")).sendKeys("joyobayagbonna@gmail.com");
    driver.findElement(By.id("accountResetPasswordButton")).click();
    driver.close();
  }
  @Test
  public void nopassword() {
    driver.get("https://www.quickteller.com/");
    driver.manage().window().setSize(new Dimension(1074, 824));
    driver.findElement(By.cssSelector(".btn__login")).click();
    driver.findElement(By.id("accountLoginFormUsername")).click();
    driver.findElement(By.id("accountLoginFormUsername")).sendKeys("joy.obayagbonna@yahoo.com");
    driver.findElement(By.id("accountLoginFormButton")).click();
    driver.close();
  }
  @Test
  public void usernameisempty() {
    driver.get("https://www.quickteller.com/");
    driver.manage().window().setSize(new Dimension(1074, 824));
    driver.findElement(By.cssSelector(".btn__login")).click();
    driver.findElement(By.id("accountLoginFormPassword")).click();
    driver.findElement(By.id("accountLoginFormPassword")).sendKeys("Bernice2017");
    driver.findElement(By.id("accountLoginFormButton")).click();
    driver.findElement(By.id("accountLoginFormButton")).click();
    driver.findElement(By.id("accountLoginFormButton")).click();
    driver.findElement(By.id("accountLoginFormButton")).click();
    driver.close();
  }
}
